language: go

env:
  - GO111MODULE=on

go:
  - 1.12.x
  - tip

os:
  - linux

services:
  - docker

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

branches:
  only:
    - master

install:

script:
  - make build style test codecov

